name: Check Changelog

on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  pull-requests: read

jobs:
  changelog-check:
    name: Changelog Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Verify Changelog is Updated
        run: |
          if ! git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q '^CHANGELOG\.md$'; then
            echo "No changelog update detected!"
            exit 1
          else
            echo "Changelog has been updated."
          fi

      - name: Check for new changelog entries in PR body
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          if ! echo "$PR_BODY" | grep -qi '#changelog'; then
            echo "This pull request does not include a changelog entry!"
            exit 1
          else
            echo "PR includes a changelog entry."
          fi
