name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  setup-micromamba:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-name: myenv
          create-args: >-
            python=3.12
          init-shell: bash

      - name: Check Micromamba Installation
        run: micromamba --version

  call-version-info-workflow:
    needs: setup-micromamba
    uses: ASFHyP3/actions/.github/workflows/reusable-version-info.yml@v0.15.0
    with:
        python_version: '3.12'

  call-docker-ghcr-workflow:
    needs: call-version-info-workflow
    uses: ASFHyP3/actions/.github/workflows/reusable-docker-ghcr.yml@v0.15.0
    with:
      version_tag: ${{ needs.call-version-info-workflow.outputs.version_tag }}
      user: ${{ github.actor }}
      release_branch: main     
      develop_branch: dev  
      file: Dockerfile 
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
