name: Pytest

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  # https://github.com/pytest-dev/pytest/issues/2042#issuecomment-429289164
  PY_IGNORE_IMPORTMISMATCH: 1

jobs:
  pytest:
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: opera_tropo
          environment-file: environment.yml
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          micromamba activate opera_tropo
          python -m pip install --no-deps .

      - name: Run tests with Pytest
        run: |
          micromamba activate opera_tropo
          pytest . --maxfail=1 --disable-warnings -v
